### PR TITLE
Use proper types for HTMLform properties

### PR DESCRIPTION
**Pull request by garyb**
Will resolve slamdata/purescript-halogen#433

### CODE REVIEW

**Comment by garyb** [comment]
@natefaubion this really is a breaking change, I guess we'll have to bump Halogen to v2.0 too 😕 

I did a quick scan through to see if there were any other obvious stringly-typed properties that shouldn't be, but didn't see any. Maybe you could have a look through too to double check?

**Comment by natefaubion** [comment]
I would not consider this a breaking change, as it was unusable before. This is correcting the definition.

**Comment by garyb** [comment]
Fair enough, I did consider that argument also. Could breaking-bump this and then patch-bump Halogen perhaps? That way at least if anyone else is depending on this they'll know about the conflict at "dependency time".

**Comment by natefaubion** [comment]
I'm fine with that.

**Pull request merged**
